### ISSUE TITLE
Updated?

### ISSUE THREAD

**Issue by mdestafadilah** [t18d/nG-SetEnvIf#4]
This will be updated to other version up?

**Comment by tkb-github** [comment]
On versioning

> MAJOR now refers to the _n_ in nG, MINOR to _x_ in upstream version number v1.x, and PATCH represents local fixes

So, both major and minor versions are incremented in lockstep with Jeff Starr’s nG Firewall. Patch version gets bumped as we incorporate bug fixes or improvements (which are also contributed back to upstream).

**Comment by mdestafadilah** [comment]
> On versioning
> 
> > MAJOR now refers to the _n_ in nG, MINOR to _x_ in upstream version number v1.x, and PATCH represents local fixes
> 
> So, both major and minor versions are incremented in lockstep with Jeff Starr’s nG Firewall. Patch version gets bumped as we incorporate bug fixes or improvements (which are also contributed back to upstream).

I was using 7G but, i can't upgrade to 8G with this repo, any idea?

**Comment by tkb-github** [comment]
You can – just remove 7G and follow the instructions to install the right files for your server. Make sure you’ve tested it with logging turned on so you know which rule blocks a legitimate request if that happens.

Anything that blocks a smooth upgrade path is treated as a bug. Open an issue and we’ll get it fixed.

**Comment by mdestafadilah** [comment]
> You can – just remove 7G and follow the instructions to install the right files for your server. Make sure you’ve tested it with logging turned on so you know which rule blocks a legitimate request if that happens.
> 
> Anything that blocks a smooth upgrade path is treated as a bug. Open an issue and we’ll get it fixed.

No, i try in exist 7G not luck try like your direction before, but my nginx can't load start, i try in clone server as production, it's show 404 Page in my Logout routes apps.

> APP_PATH/login/logout

8G blocked yea?

**Comment by tkb-github** [comment]
`nginx -t` usually gives you clues about what’s wrong with your config.

If you still can’t figure it out, paste the output of this command here.
