### ISSUE TITLE
Desideratum: Porting to Cloudflare's free-tier WAF

### ISSUE THREAD

**Issue by mdestafadilah** [t18d/nG-SetEnvIf#7]
Desideratum: Porting to Cloudflare's free-tier WAF

any tutorial how do in cloudflare?

**Comment by tkb-github** [comment]
See https://community.cloudflare.com/t/add-7g-firewall-list-to-waf/398266/2

Note that 

1. Some rules are more portable than others. The trick is to convert the regex (which isn’t available in Free) to compound expression.
2. The maximum length of a rule expression is 4,096 characters.

**Comment by mdestafadilah** [comment]
Thanks!

but, 

1. Some rules are more portable than others. The trick is to convert the regex (which isn’t available in Free) to compound expression.

so it's not cover at all right? no problem.

**Comment by tkb-github** [comment]
Correct. That’s why we removed this from README.

**Comment by mdestafadilah** [comment]
all right, it's clear now, thanks btw.
